### PR TITLE
Lookaround! mod compatibility

### LINKED ISSUE #11: drawTexture for default case is called with modified args in InGameHudMixin leading to mod incompatibility
There is a problem that the original arguments are not passed to the `drawTexture` method, and this causes incompatibility with other mods

https://github.com/ZaOrlando/crosshairmod/blob/0b70fee378b8019fa178ba949733b9f7da311b00/src/main/java/zaorlando/crosshairmod/mixin/InGameHudMixin.java#L33-L56

For example, if some other mod modifies `x` and `y` arguments, this mod replaces this modifications with own values

https://github.com/ZaOrlando/crosshairmod/blob/0b70fee378b8019fa178ba949733b9f7da311b00/src/main/java/zaorlando/crosshairmod/mixin/InGameHudMixin.java#L45

### PR DESCRIPTION
**Pull request by qualterz**
Partially resolves #11 and fixes a crash with the [Lookaround!](https://github.com/qualterz/lookaround) mod

### CODE REVIEW

**Comment by KiOrlando** [comment]
This seems like a weird fix for a crash to me. Is your repo up to date? If so, I'd like to see the crash log, and if not can you commit your new changes?

**Comment by KiOrlando** [comment]
I wont be able to do anything to fix this today, but I look more into this tomorrow,

**Comment by qualterz** [comment]
It is a really weird fix, but this done due to the mixin mechanics. You can test it with my [mod](https://github.com/qualterz/lookaround) and you will see that crash magically disappear. I tried to find some [documentation](https://github.com/SpongePowered/Mixin/wiki) to realize why this working it that way but nothing found

**Comment by qualterz** [comment]
Crashes without this patch
<details open>
<summary>Crash report</summary>
<br>
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 6/26/22, 7:20 PM
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.client.util.math.MatrixStack cannot be cast to class java.lang.Integer (net.minecraft.client.util.math.MatrixStack is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a57ae10; java.lang.Integer is in module java.base of loader 'bootstrap')
	at net.minecraft.client.gui.hud.InGameHud.args$zep000$modifyDrawTextureArgs(InGameHud.java:2023)
	at net.minecraft.client.gui.hud.InGameHud.renderCrosshair(InGameHud.java:457)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:235)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.hud.InGameHud.args$zep000$modifyDrawTextureArgs(InGameHud.java:2023)
	at net.minecraft.client.gui.hud.InGameHud.renderCrosshair(InGameHud.java:457)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:235)
</details>

**Comment by KiOrlando** [comment]
Im not seeing the crash you are mentioning, both are working correctly. How was this triggered and which mc version were you using? 1.19 compat is still in the works,

**Comment by qualterz** [comment]
Weird, i hope that the problem is only in my development environment

**Comment by KiOrlando** [comment]
For reference, I was running v0.4.5 of this mod (the latest build of curseforge) and a build from commit [ff9cc739e3f97d72a76022998e6d3425d2156a55](https://github.com/qualterz/lookaround/tree/ff9cc739e3f97d72a76022998e6d3425d2156a55) of your mod, which is the latest that seems to support 1.18.

I also tested outside of a dev environment, aka I made a mc instance and installed the mod like a user would have.

**Comment by KiOrlando** [comment]
You can also try changing this line to `@Mixin(value = InGameHud.class, priority = 999)` or `@Mixin(value = InGameHud.class, priority = 1001)` 

I'm not sure if this will have any effect, but it could help. I wont be able to do any more today, Ill check back here some point tonight. 

https://github.com/qualterz/lookaround/blob/ff9cc739e3f97d72a76022998e6d3425d2156a55/src/main/java/me/qualterz/minecraft/lookaround/mixin/InGameHudMixin.java#L17

**Comment by qualterz** [comment]
I forgot to note that the crash happens only when you press or hold `Left Alt` while playing with my mod

**Comment by KiOrlando** [comment]
That wouldn't change anything, I was testing the functionalities of both mods. Pressing left alt didn't crash for me, both mods seemed to work exactly as intended.

**Comment by qualterz** [comment]
Ok, if it works fine outside the development environment, you can close this pull request

**Pull request closed without merging**
